Data_Process: ./ProcessedFolder/
Epoch: 400
attention_droput: 0.0
batch_size: 1
embedding_size: 256
eps: 1.0e-12
hidden_dropout_prob: 0.0
image_size: 256
initializer_range: 0.02
lr: 0.01
mlp_ratio: 4
num_Channle: 1
num_classes: 2
num_heads: 8
num_hidden_layers: 4
num_workers: 2
patch_size: 16
qkv_bias: true
weight_decay: 0.01
